---
title: "Working final project graphs_Aguilar"
author: "Cynthia"
date: "2/27/2021"
output: html_document
---

```{r, echo=FALSE}
library(tidyverse)    
library(lubridate)    
library(openintro)     
library(maps)          
library(ggmap)         
library(gplots)       
library(RColorBrewer)  
library(sf)            
library(leaflet)       
library(ggthemes)      
library(plotly)        
library(gganimate)    
library(transformr)    
library(gifski)        
library(shiny)         
library(ggimage)
library(tidytuesdayR)
theme_set(theme_minimal())
```

```{r,echo=FALSE}
# College Tuition Data
tuition_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')
tuition_income <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv') 
salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')
## Including Plots
historical_tuition <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/historical_tuition.csv')
```

```{r, echo=FALSE}
# Wealth and Income Over Time
lifetime_earn <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/lifetime_earn.csv')
student_debt <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/student_debt.csv')
retirement <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/retirement.csv')
home_owner <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/home_owner.csv')
race_wealth <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/race_wealth.csv')
income_time <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_time.csv')
income_limits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_limits.csv')
income_aggregate <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_aggregate.csv')
income_distribution <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_distribution.csv')
income_mean <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_mean.csv')
```
```{r}
race_wealth %>%   
  filter(year >= "1989", race !="Non-White",type=="Median") %>% 
  left_join(retirement, by =c("race","year")) %>% 
  ggplot(aes(x= year,
             y= retirement,
             fill=race))+
  geom_histogram(stat = "identity")+
  geom_line(aes(y=wealth_family))+
  scale_x_continuous(limits = c(1989,2017), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0,200000), expand = c(0, 0),labels=scales::dollar_format())+
  scale_fill_manual(values = c("#6941e1","#4169e1", "#41b9e1"))+
  labs(title = "Average Family Liquid Retirement Savings from 1986-2016",
       caption = "*Line represents median family wealth",
       x="",
       y="")+
  theme(plot.title.position = "plot",
        legend.position = "none",
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(color = "black"),
        axis.ticks = element_line(color = 'black')) +
  facet_wrap(vars(race))
```


