---
title: 'Final Project'
author: "Kate Seeger, Cynthia Aguilar, Jennifer Huang, Chloe Nance"
output: 
  html_document:
    keep_md: TRUE
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)     # for data cleaning and plotting
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(transformr)    # for "tweening" (gganimate)
library(gifski)        # need the library for creating gifs but don't need to load each time
library(shiny)         # for creating interactive apps
library(ggimage)
library(tidytuesdayR)
theme_set(theme_minimal())
```

```{r}
# College Tuition Data
tuition_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')

tuition_income <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv') 

salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')

historical_tuition <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/historical_tuition.csv')

diversity_school <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv')
```

```{r}
# Wealth and Income Over Time
lifetime_earn <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/lifetime_earn.csv')
student_debt <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/student_debt.csv')
retirement <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/retirement.csv')
home_owner <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/home_owner.csv')
race_wealth <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/race_wealth.csv')
income_time <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_time.csv')
income_limits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_limits.csv')
income_aggregate <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_aggregate.csv')
income_distribution <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_distribution.csv')
income_mean <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_mean.csv')
```


```{r}
diversity_salary <- salary_potential %>% 
  left_join(diversity_school, by = c("name")) %>% 
  ggplot() +
  geom_point(aes(x = total_enrollment, 
                 y = stem_percent, 
                 colour = early_career_pay),
             size = 2,
             alpha = 0.33) +
  scale_color_gradient() +
  labs(title = "STEM students and their projected early career salary",
       subtitle = "State: {closest_state}",
       x = "Total enrollment",
       y = "Percent of STEM students",
       color = "Early career salary") + 
  theme_minimal() + 
  transition_states(state,
                    transition_length = 50,
                    state_length = 60)

animate(diversity_salary,
        duration = 500)
anim_save("stem_early_career_pay.gif")
diversity_salary
```



```{r}
race_wealth %>%  
  filter(year >= "1989", race !="Non-White",type=="Median") %>% 
  left_join(retirement, by =c("race","year")) %>% 
  ggplot(aes(x= year,
             y= retirement,
             fill=race))+
  geom_histogram(stat = "identity")+
  geom_line(aes(y=wealth_family))+
  scale_y_continuous(labels=scales::dollar_format())+
  scale_fill_manual(values = c("#6941e1","#4169e1", "#41b9e1"))+
  labs(title = "Average Family Liquid Retirement Savings from 1986-2016",
       caption = "*Line represents median family wealth",
       x="",
       y="")+
  theme(plot.title.position = "plot",
        legend.position = "none",
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(color = "black")) +
  facet_wrap(vars(race))
```



```{r}
debt_retirement <- student_debt %>%  
  left_join(retirement, by =c("race","year")) %>% 
  ggplot() +
  geom_boxplot(aes(x= loan_debt,
             y= retirement,
             fill=race)) +
  scale_y_continuous(labels=scales::dollar_format()) +
  scale_fill_manual(values = c("#40E0D0","#6495ED", "#9370DB")) +
  labs(title = "Projected Average Retirement Savings Based on Student Loan Debt",
       x="",
       y="") +
  theme(plot.title.position = "plot",
        legend.position = "none",
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(color = "black")) +
  facet_wrap(vars(race))

debt_retirement
```



