---
title: "FP Chloe graphs"
date: "3/3/2021"
output: html_document
theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)    
library(lubridate)    
library(openintro)     
library(maps)          
library(ggmap)         
library(gplots)       
library(RColorBrewer)  
library(sf)            
library(leaflet)       
library(ggthemes)      
library(plotly)        
library(gganimate)    
library(transformr)    
library(gifski)        
library(shiny)         
library(ggimage)
library(tidytuesdayR)
theme_set(theme_minimal())
```

```{r, echo=FALSE}
# College Tuition Data
tuition_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')
tuition_income <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv') 
salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')
diversity_school <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv')
## Including Plots
historical_tuition <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/historical_tuition.csv')


# Wealth and Income Over Time
lifetime_earn <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/lifetime_earn.csv')
student_debt <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/student_debt.csv')
retirement <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/retirement.csv')
home_owner <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/home_owner.csv')
race_wealth <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/race_wealth.csv')
income_time <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_time.csv')
income_limits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_limits.csv')
income_aggregate <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_aggregate.csv')
income_distribution <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_distribution.csv')
income_mean <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-09/income_mean.csv')
```


```{r}
states_map <- map_data("state")

state_center <- tibble(state = str_to_lower(state.name),
                       long = state.center$x,
                       lat = state.center$y)

tuition_cost %>%
  mutate(state = str_to_lower(state)) %>%
  group_by(state) %>% 
  summarise(in_state_avg = mean(in_state_total)) %>%
  left_join(state_center, by = "state") %>% 
  ggplot() +
  geom_map(map = states_map,
           aes(map_id = state,
               fill = in_state_avg)) +
  geom_label(aes(x = long, 
                 y = lat,
                 label = paste("$", round(in_state_avg/1000),"K", sep = "")),
             fill = "black", 
             color = "white", 
             size = 2.5) + 
  expand_limits(x = states_map$long, y = states_map$lat) + 
  scale_fill_viridis_c(option = "inferno", labels=scales::dollar_format()) +
  labs(title = "Average In State Tuition per State",
       caption = "Author: Chloe Nance",
       fill = "Average Cost") +
  theme_map() +
  theme(plot.title = element_text(face = "bold", hjust = .5, size = 15),
        plot.caption = element_text(face = "bold", size = 9),
        legend.title = element_text(face = "bold"))
```


```{r}
states_map <- map_data("state")
  
state_center <- tibble(state = str_to_lower(state.name),
                       long = state.center$x,
                       lat = state.center$y)
  
tuition_cost %>%
  mutate(state = str_to_lower(state)) %>%
  group_by(state) %>% 
  summarise(out_state_avg = mean(out_of_state_total)) %>% 
  left_join(state_center, by = "state") %>% 
  filter(state != c("Alaska", "Hawaii")) %>% 
  ggplot() +
  geom_map(map = states_map,
           aes(map_id = state,
              fill = out_state_avg)) +
  geom_label(aes(x = long, 
                 y = lat, 
                 label = paste("$", round(out_state_avg/1000), "K", sep = "")), 
             fill = "black", 
             color = "white", 
             size = 2.5) +
  expand_limits(x = states_map$long, y = states_map$lat) + 
  scale_fill_viridis_c(option = "inferno",labels=scales::dollar_format()) +
  labs(title = "Average Out of State Tuition per State",
       caption = "Author: Chloe Nance",
       fill = "Average Cost") +
  theme_map() +
  theme(plot.title = element_text(face = "bold", hjust = .5, size = 15),
        plot.caption = element_text(face = "bold", size = 9),
        legend.title = element_text(face = "bold"))
```


```{r}
states_map <- map_data("state")

options(scipen=10000)

diversity_school %>%
  mutate(state = str_to_lower(state)) %>% 
  group_by(state) %>% 
  filter(category %in% c("Black", "White", "Hispanic", "Total Minority")) %>% 
  ggplot() +
  geom_map(map = states_map,
           aes(map_id = state,
               fill = enrollment)) +
  expand_limits(x = states_map$long, y = states_map$lat) + 
  scale_fill_viridis_c(option = "inferno") +
  labs(title = "Diversity enrollment in US colleges",
       caption = "Author: Chloe Nance",
       fill = "Enrollment") +
  facet_wrap(~category) +
  theme_map() +
  theme(plot.title = element_text(face = "bold", hjust = .5, size = 15),
        plot.caption = element_text(face = "bold", size = 9),
        legend.title = element_text(face = "bold"),
        legend.box.background = element_rect(),
        legend.box.margin = margin(6, 6, 6, 6),
        legend.position = "right")
```




## Student loan debt based on racial group

```{r, echo=FALSE}
student_debt %>% 
  ggplot(aes(x = year, y = loan_debt, color = race)) +
  geom_line() +
  scale_color_manual(values = c("#9370DB","#6495ED", "#40E0D0")) + 
  scale_y_continuous(limits = c(0, 18000), expand = c(0, 0),labels=scales::dollar_format()) + 
  labs(title = "Student Loan Debt Based on Racial Groups",
       caption = "Author: Chloe Nance",
       x="",
       y="",
       color = "")
```
